apiVersion: v1
kind: Pod
metadata:
  name: test-root-pod
spec:
  containers:
    - name: test
      image: alpine
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsNonRoot: false 
  restartPolicy: Never

