name: Snyk Multiservice Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  scan-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - account-service
          - analytics-service
          - transaction-service
          - user-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies for ${{ matrix.service }}
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.service }}/requirements.txt

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Build Docker image
      run: docker build -t securebanking/${{ matrix.service }}:latest ${{ matrix.service }}

    - name: Confirm image exists
      run: docker images | grep securebanking/${{ matrix.service }}

    - name: Snyk Docker scan (fail only on high+)
      uses: snyk/actions/docker@0.4.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: securebanking/${{ matrix.service }}:latest
        args: --file=${{ matrix.service }}/Dockerfile --severity-threshold=high
      continue-on-error: true

