name: Snyk Multiservice Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - account-service
          - analytics-service
          - transaction-service
          - user-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies for ${{ matrix.service }}
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.service }}/requirements.txt

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Auth Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Build Docker image
      run: docker build -t securebanking/${{ matrix.service }}:latest ${{ matrix.service }}

    - name: Snyk Docker scan + SARIF output
      run: |
        snyk test --docker securebanking/${{ matrix.service }}:latest \
        --file=${{ matrix.service }}/Dockerfile \
        --severity-threshold=high \
        --sarif-file-output=snyk-${{ matrix.service }}.sarif || true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Upload SARIF to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-${{ matrix.service }}.sarif

